project:
  type: website
  output-dir: _site

website:
  title: "Hasan's Data Science & AI Blog"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Series"
        menu:
          - text: "Data Science Steps"
            file: posts/series/data-science-steps.qmd
          - text: "Computer Vision Foundations"
            file: posts/series/computer-vision-foundations.qmd
          - text: "VLM Series"
            file: posts/series/vlm.qmd
          - text: "Anomaly Detection"
            file: posts/series/anomaly-detection/index.qmd
      - text: "Categories"
        file: categories.qmd
      - text: "Tags"
        file: tags.qmd
      - text: "About"
        file: about.qmd
    right:
      - icon: github
        href: https://github.com/HasanGoni
      - icon: twitter
        href: https://twitter.com/hasangoni

  sidebar:
    style: "docked"
    contents:
      - section: "Data Science"
        collapse: true
        collapsed: true
        contents:
          - posts/series/data-science-steps.qmd
          - posts/data-science-steps-to-follow-part01/index.qmd
          - posts/data-science-steps-to-follow-part02/index.qmd
          - posts/data-science-steps-to-follow-part03/index.qmd
          - posts/data-science-steps-to-follow-part04/index.qmd
          - posts/data-science-steps-to-follow-part05/index.qmd
          - posts/data-science-steps-to-follow-part06/index.qmd
      - section: "Computer Vision Foundations"
        collapse: true
        collapsed: true
        contents:
          - posts/series/computer-vision-foundations.qmd
          - text: "1. Why Computer Vision?"
            href: posts/series/cv-foundations/01-why-computer-vision.qmd
          - text: "2. Images as Data"
            href: posts/series/cv-foundations/02-images-as-data.qmd
          - text: "3. OpenCV Essentials"
            href: posts/series/cv-foundations/03-opencv-essentials.qmd
          - text: "4. Finding Patterns"
            href: posts/series/cv-foundations/04-finding-patterns.qmd
          - text: "5. Image Segmentation"
            href: posts/series/cv-foundations/05-image-segmentation.qmd
          - text: "6. Feature Magic"
            href: posts/series/cv-foundations/06-feature-magic.qmd
          - text: "7. Why Deep Learning?"
            href: posts/series/cv-foundations/07-why-deep-learning.qmd
          - text: "8. Modern Vision Models"
            href: posts/series/cv-foundations/08-modern-vision-models.qmd
          - text: "9. First CV Project"
            href: posts/series/cv-foundations/09-first-cv-project.qmd
          - text: "10. Where to Go Next"
            href: posts/series/cv-foundations/10-where-to-go-next.qmd
      - section: "Anomaly Detection"
        collapse: true
        collapsed: true
        contents:
          - text: "Introduction"
            href: posts/series/anomaly-detection/index.qmd
          - text: "Finding the Oddballs"
            href: posts/series/anomaly-detection/finding-the-oddballs.qmd
      - section: "VLM Series"
        collapse: true
        collapsed: true
        contents:
          - text: "Introduction"
            href: posts/series/vlm.qmd
          - text: "Qwen3-14B"
            href: posts/series/vlm-qwen3-14b/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true
    highlight-style: github
