project:
  type: website

website:
  title: "Hasan Blog Post"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/HasanGoni
      - icon: twitter
        href: https://twitter.com/hasangoni
    left:
      - text: "Blog"
        href : blog/index.qmd
format:
  html:
    theme: cosmo
    css: styles.css



