"""Real, reduced training loop for RAU's fusion mechanism against a real
Qwen2.5-VL-3B + real SAM2, on real CAMUS data.

Matches the paper's Section 3.3 "Training Setting" (SFT phase): "we jointly
train the embeddings of the <Seg> tokens generated by the VLM, the MLP
projection layer, and the SAM2 decoder under segmentation supervision, while
freezing the other VLM weights." We implement exactly that — everything else
(the VLM backbone, SAM2's vision encoder/prompt encoder) stays frozen. The
paper's second stage (GRPO/RL on top of this) is not implemented — that's a
much larger undertaking (custom reward, policy optimization loop) and
orthogonal to whether the fusion mechanism itself works, which is what this
demonstrates.

Run:
    uv run train_rau.py --bank reference_bank.pt --steps 60
"""
from __future__ import annotations

import argparse
import io
import json
import random
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image
from transformers import AutoImageProcessor, AutoModel

from camus_data import LABELS, download_camus, list_patients, load_frame_pair
from rau_model import RAU
from rau_modules import ReferenceBank, dice_loss, retrieve_reference

LABEL_NAMES = {1: "left ventricular myocardium", 2: "left ventricle", 3: "left atrium"}

PROMPT_TEMPLATE = (
    "The first image is a reference echocardiogram with the {label} region known. "
    "The second image is a different (or the same) patient's echocardiogram. "
    "Identify and locate the {label} in the second image. Respond with the segmentation token."
)


@torch.no_grad()
def dino_embed(image, dino, dino_proc, device):
    inputs = dino_proc(images=image, return_tensors="pt").to(device)
    return dino.forward(**inputs).pooler_output[0]


def train(bank_path: Path, steps: int, out_dir: Path, device: str, cache_dir: Path, n_train_patients: int, offset: int):
    bank = ReferenceBank.load(bank_path).to(device)

    img_dir, mask_dir = download_camus(cache_dir)
    patients = list_patients(img_dir, mask_dir)
    train_patients = patients[offset:offset + n_train_patients]
    print(f"{len(train_patients)} real CAMUS patients for training (disjoint from the {offset} used to build the reference bank)")

    model = RAU()
    dino = AutoModel.from_pretrained("facebook/dinov2-base").to(device).eval()
    dino_proc = AutoImageProcessor.from_pretrained("facebook/dinov2-base")

    optimizer = torch.optim.AdamW(model.trainable_parameters(), lr=2e-4)

    examples = []
    for img_path, mask_path, pid in train_patients:
        _, _, tgt_img, tgt_mask = load_frame_pair(img_path, mask_path, ref_frame=0, target_frame=-1)
        present = [c for c in np.unique(tgt_mask) if c in LABELS]
        for c in present:
            examples.append((tgt_img, tgt_mask, int(c)))
    random.Random(0).shuffle(examples)
    print(f"{len(examples)} (target image, label) training examples")

    fixed_target_img, fixed_target_mask, fixed_label = examples[0]
    fixed_ref_idx = retrieve_reference(dino_embed(fixed_target_img, dino, dino_proc, device), bank)

    out_dir.mkdir(parents=True, exist_ok=True)
    losses = []
    gif_frames = []

    for step in range(steps):
        tgt_img, tgt_mask, label = examples[step % len(examples)]

        tgt_dino = dino_embed(tgt_img, dino, dino_proc, device)
        ref_idx = retrieve_reference(tgt_dino, bank)
        memory_vectors = bank.memory_vectors[ref_idx]
        if label not in memory_vectors:
            continue

        # Reference image itself isn't stored (only its bank vectors are) to
        # keep the bank small; re-derive a stand-in reference frame from the
        # same retrieval pool for the VLM's second input image slot. In
        # practice you'd cache the reference images alongside their vectors.
        ref_img_path, ref_mask_path, _ = patients[ref_idx]
        ref_img, _, _, _ = load_frame_pair(ref_img_path, ref_mask_path, ref_frame=0, target_frame=0)

        prompt = PROMPT_TEMPLATE.format(label=LABEL_NAMES[label])
        h_seg = model.get_seg_hidden_state(ref_img, tgt_img, prompt)

        q = model.projection(h_seg.unsqueeze(0)).squeeze(0)
        from rau_modules import memory_attention
        z = memory_attention(q, memory_vectors)

        sam_inputs = model.sam2_processor(images=tgt_img, return_tensors="pt").to(model.vlm.device)
        target_embedding = z.to(model.sam2.dtype).view(1, 1, 1, -1)
        outputs = model.sam2(**sam_inputs, target_embedding=target_embedding, multimask_output=False)
        pred_logits = outputs.pred_masks[0, 0].squeeze()  # (h, w) low-res

        gt = torch.from_numpy((tgt_mask == label).astype(np.float32)).to(model.vlm.device)
        gt_resized = F.interpolate(gt[None, None], size=pred_logits.shape[-2:], mode="nearest")[0, 0]

        bce = F.binary_cross_entropy_with_logits(pred_logits.float(), gt_resized)
        dice = dice_loss(pred_logits.float().unsqueeze(0), gt_resized.unsqueeze(0))
        loss = bce + dice

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        losses.append(loss.item())

        if step % 5 == 0 or step == steps - 1:
            print(f"step {step:3d}/{steps}  loss {loss.item():.4f}  (bce {bce.item():.4f} dice {dice.item():.4f})  label={LABEL_NAMES[label]}")

        if step % max(1, steps // 20) == 0 or step == steps - 1:
            gif_frames.append(_render_frame(model, bank, patients, fixed_ref_idx, fixed_target_img, fixed_label, step))

    plt.figure(figsize=(6, 4))
    plt.plot(losses)
    plt.xlabel("training step")
    plt.ylabel("loss (bce + dice)")
    plt.title("RAU fusion training loss (real Qwen2.5-VL-3B + SAM2, real CAMUS)")
    plt.tight_layout()
    plt.savefig(out_dir / "loss_curve.png", dpi=130)

    gif_frames[0].save(
        out_dir / "training_progress.gif", save_all=True,
        append_images=gif_frames[1:] + [gif_frames[-1]] * 4, duration=500, loop=0,
    )
    (out_dir / "losses.json").write_text(json.dumps(losses))
    print(f"Saved loss curve + training_progress.gif -> {out_dir}")


@torch.no_grad()
def _render_frame(model, bank, patients, ref_idx, target_img, label, step) -> Image.Image:
    ref_img_path, ref_mask_path, _ = patients[ref_idx]
    ref_img, _, _, _ = load_frame_pair(ref_img_path, ref_mask_path, ref_frame=0, target_frame=0)
    prompt = PROMPT_TEMPLATE.format(label=LABEL_NAMES[label])
    h_seg = model.get_seg_hidden_state(ref_img, target_img, prompt)
    q = model.projection(h_seg.unsqueeze(0)).squeeze(0)
    from rau_modules import memory_attention
    z = memory_attention(q, bank.memory_vectors[ref_idx])

    sam_inputs = model.sam2_processor(images=target_img, return_tensors="pt").to(model.vlm.device)
    target_embedding = z.to(model.sam2.dtype).view(1, 1, 1, -1)
    outputs = model.sam2(**sam_inputs, target_embedding=target_embedding, multimask_output=False)
    pred = outputs.pred_masks[0, 0].squeeze().sigmoid().float().cpu().numpy()
    pred_up = np.array(Image.fromarray((pred * 255).astype(np.uint8)).resize(target_img.size)) > 127

    base = np.array(target_img).astype(np.float32)
    overlay = base.copy()
    overlay[pred_up] = overlay[pred_up] * 0.4 + np.array([255, 60, 60]) * 0.6
    frame = Image.fromarray(overlay.astype(np.uint8))

    fig, ax = plt.subplots(figsize=(4, 4))
    ax.imshow(frame)
    ax.set_title(f"step {step}", fontsize=10)
    ax.axis("off")
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=100, bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return Image.open(buf).convert("RGB")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--bank", type=Path, default=Path("reference_bank.pt"))
    ap.add_argument("--steps", type=int, default=60)
    ap.add_argument("--out", type=Path, default=Path("train_out"))
    ap.add_argument("--cache-dir", type=Path, default=Path("camus_cache"))
    ap.add_argument("--n-train-patients", type=int, default=40)
    ap.add_argument("--offset", type=int, default=30, help="skip the patients used to build the reference bank")
    ap.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    args = ap.parse_args()
    train(args.bank, args.steps, args.out, args.device, args.cache_dir, args.n_train_patients, args.offset)
